import { store } from '../core/storage.js';
import { FEVER_T, LOSE_Y, W } from '../config.js';
import { GAMEPLAY } from '../settings.js';
import { MAXT } from '../config.js';
/** Owns run data. Controllers receive this instance explicitly; nothing is kept on window. */
export function createGameState(storage = store) {
  const game = {};
  game.elapsed = 0;
  game.phase = 'title';
  game.paused = false;
  game.bodies = [];
  game.parts = [];
  game.popups = [];
  game.rings = [];
  game.rays = [];
  game.banner = null;
  game.dying = null;
  game.merging = [];
  game.iris = null;
  game.shoot = null;
  game.physicsAccumulator = 0;
  game.score = 0;
  game.best = storage.get('best', 0);
  game.bestBase = game.best;
  game.newBest = false;
  game.displayScore = 0;
  game.lastScoreText = '';
  game.dropXs = [];
  game.goldTime = 0;
  game.comboCount = 0;
  game.comboTime = 0;
  game.charge = 0;
  game.dropCooldown = 0;
  game.queuedDrop = false;
  game.canSwap = true;
  game.pickCount = 0;
  game.nextBodyId = 0;
  game.merges = 0;
  game.drops = 0;
  game.held = null;
  game.nextTier = 0;
  game.carrierX = W / 2;
  game.aimX = W / 2;
  game.carrierVelocity = 0;
  game.swing = 0;
  game.didDrop = false;
  game.didMerge = false;
  game.didSwap = false;
  game.hints = new Set();
  game.shakeMagnitude = 0;
  game.quakeTime = 0;
  game.freeze = 0;
  game.flashOpacity = 0;
  game.danger = false;
  game.loseY = LOSE_Y;
  game.attractT = 0;
  game.highestTier = 0;
  game.pace = 1;
  game.lastNb = null;
  game.swaps = 0;
  game.runTime = 0;
  game.lastSpecialDrop = 0;
  game.daily = null;
  game.rand = Math.random;
  game.bestStart = game.best;
  game.bestAnnounced = false;
  game.runStats = { fevers: 0, specials: 0, suns: 0, combo: 0 };
  game.theme = 6;
  game.mut = null;
  game.fuse = 2;
  game.feverLen = FEVER_T;
  game.swapsCap = GAMEPLAY.swapsMax;
  game.bAvg = 0;
  game.feverCharge = 0;
  game.feverT = 0;
  game.heartbeatTime = 0;
  game.themeFrom = -1;
  game.themeK = 1;
  game.mission = null;
  game.missionIndex = 0;
  game.missionsDone = 0;
  game.discoveries = 0;
  game.dex = [];
  game.spSeen = {};
  game.iceTime = 0;
  game.bolts = [];
  const savedDex = storage.get('dex', [0]);
  for (const tier of Array.isArray(savedDex) ? savedDex : [0])
    if (Number.isInteger(tier) && tier >= 0 && tier <= MAXT) game.dex[tier] = true;
  game.dex[0] = true;
  return game;
}
